---
apiVersion: v1
kind: Pod
metadata:
 name: postgres--pod
 labels:
  type: db
  author: sunny
spec: 
 containers: 
  - name: postgres
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       value: sunny
     - name: POSTGRES_USER
       value: myuser
     - name: POSTGRES_DB
       value: sunny_db

...
